# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Ian Shi
email: ian.shi@mail.utoronto.ca
description: > # this means to ignore newlines until "url:"
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with a modified <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.


url: # the base hostname & protocol for your site
baseurl: /~ruiashi # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: IanShi1996
twitter_username: ianshi3
linkedin_username: ruian-shi-4b5215b9
scholar_authorid: p7GXhskAAAAJ

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  publications:
  projects:

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
